config/routes.rb
Rails.application.routes.draw do
  resources :people

  resources :life_events

  resources :schools
  
  resources :photos

  root 'home_controller#index'

end

app/models/people.rb
class People < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :life_events
  has_many :schools	
  validates :name, presence: true
  
  def to_s
    name
  end
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:name)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>&nbsp|&nbsp<%= link_to 'Show Schools', schools_path %>&nbsp|&nbsp<%= link_to 'Show Life Events', life_events_path %>
&nbsp|&nbsp<%=link_to 'Home', root_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show">

  <p>
    <strong>Name:</strong>
    <%= @person.name %>
  </p>
  <p>
    <strong>Life Events:</strong>
    <ul>
      <% @person.life_events.order(:year).reverse_order.each do |life_event| %>
      <li>
        <%= life_event.title %> : <%= life_event.year %>
        <%= link_to "Edit", edit_life_event_path(life_event) %>
      </li>
      <% end %>
    </ul>
  </p>
  <p>
    <strong>Schools:</strong>
    <ul>
      <% @person.schools.order(:ending_year).reverse_order.each do |school| %>
      <li>
        <%= school.name %> : <%= school.beginning_year %> - <%= school.ending_year %>
        <%= link_to "Edit", edit_school_path(school) %>
      </li>
      <% end %>
    </ul>
  </p>
</div>
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>&nbsp|&nbsp<%=link_to 'Home', root_path %>