life_tracker/config/routes.rb
Rails.application.routes.draw do
  resources :people

  resources :schools

  resources :life_events

end

life_tracker/app/models/life_event.rb
class LifeEvent < ActiveRecord::Base
   belongs_to :people
   def to_s
     name
   end
end

life_tracker/app/controllers/life_events_controller.rb
class LifeEventsController < ApplicationController
  before_action :set_life_event, only: [:show, :edit, :update, :destroy]

  # GET /life_events
  # GET /life_events.json
  def index
    @life_events = LifeEvent.all
  end

  # GET /life_events/1
  # GET /life_events/1.json
  def show
  end

  # GET /life_events/new
  def new
    @life_event = LifeEvent.new
  end

  # GET /life_events/1/edit
  def edit
  end

  # POST /life_events
  # POST /life_events.json
  def create
    @life_event = LifeEvent.new(life_event_params)

    respond_to do |format|
      if @life_event.save
        format.html { redirect_to @life_event, notice: 'Life event was successfully created.' }
        format.json { render :show, status: :created, location: @life_event }
      else
        format.html { render :new }
        format.json { render json: @life_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /life_events/1
  # PATCH/PUT /life_events/1.json
  def update
    respond_to do |format|
      if @life_event.update(life_event_params)
        format.html { redirect_to @life_event, notice: 'Life event was successfully updated.' }
        format.json { render :show, status: :ok, location: @life_event }
      else
        format.html { render :edit }
        format.json { render json: @life_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /life_events/1
  # DELETE /life_events/1.json
  def destroy
    @life_event.destroy
    respond_to do |format|
      format.html { redirect_to life_events_url, notice: 'Life event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_life_event
      @life_event = LifeEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def life_event_params
      params.require(:life_event).permit(:title, :date, :desc)
    end
end

life_tracker/app/helpers/life_events_helper.rb
module LifeEventsHelper
end

life_tracker/app/views/life_events/_form.html.erb
<%= form_for(@life_event) do |f| %>
  <% if @life_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@life_event.errors.count, "error") %> prohibited this life_event from being saved:</h2>

      <ul>
      <% @life_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

life_tracker/app/views/life_events/index.html.erb
<h1>Listing life_events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @life_events.each do |life_event| %>
      <tr>
        <td><%= life_event.title %></td>
        <td><%= life_event.date %></td>
        <td><%= life_event.desc %></td>
        <td><%= link_to 'Show', life_event %></td>
        <td><%= link_to 'Edit', edit_life_event_path(life_event) %></td>
        <td><%= link_to 'Destroy', life_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Life event', new_life_event_path %>

life_tracker/app/views/life_events/new.html.erb
<h1>New life_event</h1>

<%= render 'form' %>

<%= link_to 'Back', life_events_path %>

life_tracker/app/views/life_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @life_event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @life_event.date %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @life_event.desc %>
</p>

<%= link_to 'Edit', edit_life_event_path(@life_event) %> |
<%= link_to 'Back', life_events_path %>