config/routes.rb
Rails.application.routes.draw do
  resources :people

  resources :life_events

  resources :schools
  
  resources :photos

  root 'home_controller#index'

end

app/models/school.rb
class School < ActiveRecord::Base
belongs_to :person
validates :name, presence: true
validates :beginning_year, presence: true
validates :ending_year, presence: true
validates_numericality_of :ending_year , :greater_than_or_equal_to => :beginning_year
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  def index
    @schools = School.all
  end

  def show
  end

  def new
    @school = School.new
  end

  def edit
  end

  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_school
      @school = School.find(params[:id])
    end

    def school_params
      params.require(:school).permit(:name, :beginning_year, :ending_year,:city,:state, :country, :postal_code, :person_id)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.collection_select :person_id, Person.all, :id, :name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :beginning_year %><br>
    <%= f.number_field :beginning_year %>
  </div>
  <div class="field">
    <%= f.label :ending_year %><br>
    <%= f.number_field :ending_year %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  <div class="field">
     <%= f.label :state %><br>
     <%= f.text_field :state %>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>

  </div>
   </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>LET'S LIST YOUR SCHOOLS</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Name</th>
      <th>Beginning year</th>
      <th>Ending year</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td>
          <% if school.person %>
            <%= link_to school.person, school.person %>
          <% end %>
        <td><%= school.name %></td>
        <td><%= school.beginning_year %></td>
        <td><%= school.ending_year %></td>
        <td><%= school.city %></td>
        <td><%= school.state %></td>
        <td><%= school.country %></td>

        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>&nbsp|&nbsp<%= link_to 'Life Events', life_events_path %>
&nbsp|&nbsp<%= link_to 'People', people_path %>&nbsp|&nbsp<%=link_to 'Home', root_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show">
  <p>
    <strong>Person ID:</strong>
    <%= @school.person_id %>
  </p>

  <% if @school.person %>
  <p>
    <strong>Person:</strong>
    <%= link_to @school.person, @school.person %>
  </p>
  <% end %>
  <p>
    <strong>Name:</strong>
    <%= @school.name %>
  </p>

  <p>
    <strong>Beginning year:</strong>
    <%= @school.beginning_year %>
  </p>

  <p>
    <strong>Ending year:</strong>
    <%= @school.ending_year %>
  </p>
  <p>
    <strong>City:</strong>
    <%= @school.city %>
  </p>
  <p>
    <strong>State:</strong>
    <%= @school.state %>
  </p>
  <p>
    <strong>Country:</strong>
    <%= @school.country %>
  </p>
</div>
<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>